"use strict";
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const money=n=>`S/ ${Number(n).toLocaleString("es-PE")}`,label=t=>({venta:"Venta",alquiler:"Alquiler",intercambio:"Intercambio"}[t]||t);
const favs=()=>{try{return JSON.parse(localStorage.getItem("edumarket_favoritos"))||[]}catch{return[]}},isFav=id=>favs().includes(id);
function toggleFav(id){let a=favs();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem("edumarket_favoritos",JSON.stringify(a));return a.includes(id)}
function card(p){return `<article class="card" data-id="${p.id}" tabindex="0" aria-label="Ver ${p.nombre}"><div class="card-img"><span class="badge">${label(p.tipo)}</span><button class="fav ${isFav(p.id)?"active":""}" data-fav="${p.id}" aria-label="Añadir ${p.nombre} a favoritos" aria-pressed="${isFav(p.id)}">♥</button><img src="${p.imagen}" alt="${p.nombre}" loading="lazy" width="600" height="450"></div><div class="card-body"><h3>${p.nombre}</h3><span class="price">${money(p.precio)}${p.tipo==="alquiler"?" / ciclo":""}</span><span class="meta">${p.estado} · ${p.carrera}</span><span class="rating">★ ${p.rating.toFixed(1)}</span></div></article>`}
function render(list,sel){const el=$(sel);if(!el)return;el.innerHTML=list.length?list.map(card).join(""):`<div class="empty"><h3>No encontramos materiales</h3><p>Prueba con otros filtros.</p></div>`;$$(".card",el).forEach(c=>{c.addEventListener("click",e=>{if(!e.target.closest(".fav"))openProduct(+c.dataset.id)});c.addEventListener("keydown",e=>{if(["Enter"," "].includes(e.key)){e.preventDefault();openProduct(+c.dataset.id)}})});$$("[data-fav]",el).forEach(b=>b.onclick=e=>{e.stopPropagation();let on=toggleFav(+b.dataset.fav);b.classList.toggle("active",on);b.setAttribute("aria-pressed",on)})}
function openProduct(id){const p=productos.find(x=>x.id===id),m=$("#product-modal");if(!p||!m)return;$("#m-img").src=p.imagen;$("#m-img").alt=p.nombre;$("#m-type").textContent=label(p.tipo);$("#m-name").textContent=p.nombre;$("#m-price").textContent=money(p.precio)+(p.tipo==="alquiler"?" / ciclo":"");$("#m-desc").textContent=p.descripcion;$("#m-meta").textContent=`${p.estado} · ${p.categoria} · ${p.carrera}${p.curso?` · ${p.curso}`:""}`;$("#m-seller").textContent=`Publicado por ${p.vendedor} (${p.universidad}) · ${p.publicado}`;$("#m-action").textContent={venta:"Comprar",alquiler:"Alquilar",intercambio:"Intercambiar"}[p.tipo];$("#m-action").onclick=()=>toast(`Solicitud enviada a ${p.vendedor}`);m.classList.add("open");m.setAttribute("aria-hidden","false");$(".close",m).focus();document.body.style.overflow="hidden"}
function closeModal(){const m=$("#product-modal");if(m){m.classList.remove("open");m.setAttribute("aria-hidden","true");document.body.style.overflow=""}}
function toast(t){let el=$(".toast");if(!el){el=document.createElement("div");el.className="toast";el.setAttribute("role","status");document.body.append(el)}el.textContent=t;el.classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove("show"),2600)}
function initNav(){const n=$(".navbar"),t=$(".toggle"),l=$(".links");addEventListener("scroll",()=>n?.classList.toggle("is-scrolled",scrollY>8),{passive:true});if(t&&l)t.onclick=()=>{const o=l.classList.toggle("open");t.setAttribute("aria-expanded",o)}}
function initHome(){if($("#featured"))render([...productos].sort((a,b)=>b.rating-a.rating).slice(0,6),"#featured");if($("#showcase"))$("#showcase").innerHTML=[1,5,9].map(id=>card(productos.find(p=>p.id===id))).join("");const u=new Set(productos.map(p=>p.universidad)).size,r=(productos.reduce((a,p)=>a+p.rating,0)/productos.length).toFixed(1);$$("[data-stat=items]").forEach(x=>x.textContent=`${productos.length}+`);$$("[data-stat=unis]").forEach(x=>x.textContent=u);$$("[data-stat=rating]").forEach(x=>x.textContent=r)}
function initExplore(){if(!$("#products"))return;const q=$("#search"),type=$("#type"),career=$("#career"),order=$("#order"),count=$("#count");[...new Set(productos.map(p=>p.carrera))].sort().forEach(c=>career.insertAdjacentHTML("beforeend",`<option>${c}</option>`));let cat="todas";const apply=()=>{let term=q.value.trim().toLowerCase(),a=productos.filter(p=>(p.nombre+" "+p.categoria+" "+p.carrera).toLowerCase().includes(term)&&(cat==="todas"||p.categoria===cat)&&(type.value==="todos"||p.tipo===type.value)&&(career.value==="todas"||p.carrera===career.value));if(order.value==="asc")a.sort((x,y)=>x.precio-y.precio);if(order.value==="desc")a.sort((x,y)=>y.precio-x.precio);if(order.value==="rating")a.sort((x,y)=>y.rating-x.rating);count.textContent=a.length;render(a,"#products")};[q,type,career,order].forEach(x=>x.addEventListener(x===q?"input":"change",apply));$$(".chip").forEach(b=>b.onclick=()=>{$$(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");cat=b.dataset.cat;apply()});apply()}
function initPublish(){const f=$("#publish-form");if(!f)return;const update=()=>{const p={id:0,nombre:$("#title").value||"Nombre de tu material",precio:+$("#price").value||0,tipo:$("input[name=kind]:checked")?.value||"venta",estado:$("#state").value||"Estado",carrera:$("#career-input").value||"Tu carrera",imagen:$("#preview-img")?.src||"https://picsum.photos/seed/edumarket-nuevo/600/450",rating:5};$("#preview").innerHTML=card(p)};f.addEventListener("input",update);$("#photo").onchange=e=>{const file=e.target.files[0];if(file&&file.type.startsWith("image/")&&file.size<5e6){const r=new FileReader;r.onload=()=>{$("#preview-img").src=r.result;update()};r.readAsDataURL(file)}else if(file)toast("Selecciona una imagen menor de 5 MB")};f.onsubmit=e=>{e.preventDefault();if(!f.reportValidity())return;toast("Material publicado correctamente");f.reset();update()};update()}
function initProfile(){if(!$("#mine"))return;render(productos.filter(p=>p.vendedor==="Renzo Vidal"),"#mine");$("#published").textContent=productos.filter(p=>p.vendedor==="Renzo Vidal").length;$$(".tab").forEach(t=>t.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");const is=t.dataset.tab==="mine";$("#mine").hidden=!is;$("#favorites").hidden=is;if(!is)render(productos.filter(p=>isFav(p.id)),"#favorites")})}
function initDetail(){const d=$("#detail");if(!d)return;const id=Number(new URLSearchParams(location.search).get("id"))||1,p=productos.find(x=>x.id===id)||productos[0];d.innerHTML=`<div class="modal-grid"><img src="${p.imagen}" alt="${p.nombre}"><div><span class="eyebrow">${label(p.tipo)}</span><h1>${p.nombre}</h1><strong class="price">${money(p.precio)}${p.tipo==="alquiler"?" / ciclo":""}</strong><p>${p.descripcion}</p><p class="meta">${p.estado} · ${p.categoria} · ${p.carrera}${p.curso?` · ${p.curso}`:""}</p><div class="panel"><strong>${p.vendedor}</strong><p>${p.universidad} · ★ ${p.rating.toFixed(1)} · ${p.publicado}</p></div><div class="cta"><button class="btn primary" id="detail-action">${{venta:"Comprar",alquiler:"Alquilar",intercambio:"Intercambiar"}[p.tipo]}</button><button class="btn" id="detail-fav">${isFav(p.id)?"Quitar de favoritos":"Guardar en favoritos"}</button></div></div></div>`;$("#detail-action").onclick=()=>toast(`Solicitud enviada a ${p.vendedor}`);$("#detail-fav").onclick=e=>{const on=toggleFav(p.id);e.currentTarget.textContent=on?"Quitar de favoritos":"Guardar en favoritos"}}
function initAbout(){const a=$(".about");if(!a)return;const fit=()=>a.style.gridTemplateColumns=innerWidth<=900?"1fr":"repeat(3,1fr)";fit();addEventListener("resize",fit,{passive:true})}
function initLayout(){const f=$("#publish-form");if(f){f.style.minWidth="0";$$(".group",f).forEach(x=>x.style.minWidth="0");$("#photo").style.width="100%"}}
document.addEventListener("DOMContentLoaded",()=>{initNav();initHome();initExplore();initPublish();initProfile();initDetail();initAbout();initLayout();$("#login-form")?.addEventListener("submit",e=>{e.preventDefault();if(e.currentTarget.reportValidity()){toast("Ingresando...");setTimeout(()=>location.href="perfil.html",700)}});$$("[data-soon]").forEach(b=>b.onclick=()=>toast("Esta función estará disponible pronto"));$$("[data-close]").forEach(b=>b.onclick=closeModal);$("#product-modal")?.addEventListener("click",e=>{if(e.target.id==="product-modal")closeModal()});addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()})});
