const productos=[
{id:1,nombre:"Cálculo de una variable - Stewart 8va ed.",precio:65,categoria:"Libros",tipo:"venta",estado:"Buen estado",carrera:"Ingeniería",curso:"Cálculo I",descripcion:"Libro completo con anotaciones a lápiz e incluye separatas de ejercicios resueltos.",imagen:"assets/img/productos/calculo.png",rating:4.8,vendedor:"Renzo Vidal",universidad:"PUCP",publicado:"Hace 2 días"},
{id:2,nombre:"Calculadora Casio FX-991LA X",precio:15,categoria:"Electrónica",tipo:"alquiler",estado:"Como nuevo",carrera:"Ingeniería",curso:"Física General",descripcion:"Calculadora científica con todas sus funciones verificadas. Alquiler por ciclo.",imagen:"assets/img/productos/CASSIO.png",rating:4.9,vendedor:"Camila Torres",universidad:"Universidad de Lima",publicado:"Hace 5 horas"},
{id:3,nombre:"Set de tableros de dibujo técnico",precio:40,categoria:"Arte y Diseño",tipo:"intercambio",estado:"Usado",carrera:"Arquitectura",curso:"Dibujo Técnico I",descripcion:"Tablero A2 con escuadras y compás. Intercambio por materiales de maquetería.",imagen:"assets/img/productos/escuadra.png",rating:4.6,vendedor:"Diego Salazar",universidad:"UPC",publicado:"Hace 1 día"},
{id:4,nombre:"Bata de laboratorio talla M",precio:35,categoria:"Uniformes",tipo:"venta",estado:"Nuevo",carrera:"Medicina",curso:"Laboratorio Clínico",descripcion:"Bata blanca nueva, talla M, con bordado institucional removible.",imagen:"assets/img/productos/bata.png",rating:5,vendedor:"Fiorella Quispe",universidad:"UNMSM",publicado:"Hace 3 días"},
{id:5,nombre:"Guitarra clásica Yamaha C40",precio:25,categoria:"Instrumentos",tipo:"alquiler",estado:"Buen estado",carrera:"Educación",curso:"Taller de Música",descripcion:"Guitarra con cuerdas nuevas y funda básica. Alquiler mensual.",imagen:"assets/img/productos/guitarra.png",rating:4.7,vendedor:"Martín Huamán",universidad:"PUCP",publicado:"Hace 6 días"},
{id:6,nombre:"Escritorio plegable para estudio",precio:90,categoria:"Mobiliario",tipo:"venta",estado:"Como nuevo",carrera:"General",curso:"",descripcion:"Escritorio plegable de madera, ideal para espacios pequeños.",imagen:"https://picsum.photos/seed/edumarket-escritorio/600/450",rating:4.5,vendedor:"Andrea Rojas",universidad:"Universidad del Pacífico",publicado:"Hace 4 días"},
{id:7,nombre:"Código Civil comentado 2024",precio:80,categoria:"Libros",tipo:"venta",estado:"Nuevo",carrera:"Derecho",curso:"Derecho Civil III",descripcion:"Edición actualizada, nunca usada. Incluye separadores originales.",imagen:"assets/img/productos/codigo.png",rating:4.9,vendedor:"Sebastián Flores",universidad:"PUCP",publicado:"Hace 1 semana"},
{id:8,nombre:"Kit de disección completo",precio:45,categoria:"Otros",tipo:"intercambio",estado:"Buen estado",carrera:"Medicina",curso:"Anatomía",descripcion:"Kit con bisturí, pinzas y tijeras en estuche.",imagen:"assets/img/productos/kit.png",rating:4.4,vendedor:"Valeria Chumpitaz",universidad:"UNMSM",publicado:"Hace 2 días"},
{id:9,nombre:"Laptop Lenovo ThinkPad",precio:1200,categoria:"Electrónica",tipo:"venta",estado:"Usado",carrera:"Ciencias de la Computación",curso:"",descripcion:"8 GB RAM, SSD de 256 GB, batería de 4 horas y cargador original.",imagen:"assets/img/productos/laptop.png",rating:4.3,vendedor:"Renzo Vidal",universidad:"PUCP",publicado:"Hace 3 horas"},
{id:10,nombre:"Maletín porta planos A1",precio:20,categoria:"Arte y Diseño",tipo:"alquiler",estado:"Como nuevo",carrera:"Arquitectura",curso:"Taller de Diseño",descripcion:"Maletín rígido para planos A1. Alquiler semanal o mensual.",imagen:"assets/img/productos/maleta.png",rating:4.8,vendedor:"Camila Torres",universidad:"Universidad de Lima",publicado:"Hace 5 días"},
{id:11,nombre:"Bicicleta urbana aro 26",precio:350,categoria:"Deporte",tipo:"venta",estado:"Buen estado",carrera:"General",curso:"",descripcion:"Bicicleta revisada, ideal para llegar al campus.",imagen:"assets/img/productos/bici.png",rating:4.6,vendedor:"Diego Salazar",universidad:"UPC",publicado:"Hace 1 día"},
{id:12,nombre:"Microscopio biológico monocular",precio:60,categoria:"Otros",tipo:"alquiler",estado:"Buen estado",carrera:"Biología",curso:"Laboratorio de Biología",descripcion:"Microscopio con cuatro objetivos y estuche. Alquiler por ciclo.",imagen:"assets/img/productos/microscopio.png",rating:4.7,vendedor:"Fiorella Quispe",universidad:"UNMSM",publicado:"Hace 4 días"}];
